name: Deploy Gem

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.6

    - name: Install dependencies
      run: bundle install

    - name: Build gem
      run: bundle exec rake build

    - name: Publish gem to GPR
      env:
        GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
        RUBYGEMS_HOST: https://rubygems.pkg.github.com
      run: gem push --host $RUBYGEMS_HOST/$OWNER pkg/*.gem
